Login
Ajris/site pull request #9
Opened 2019-05-23 23:22 UTC by MartaSwierczewska

2019-05-23 23:31 UTC, Ajris requested changes

2019-05-23 23:31 UTC, Ajris commented on src/components/login/user.svg
> +<svg focusable="false" class="svg-inline--fa fa-user fa-w-14" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M313.6 304c-28.7 0-42.5 16-89.6 16-47.1 0-60.8-16-8
what is this?

2019-05-23 23:31 UTC, Ajris commented on src/components/login/Login.css
> +input {
save only needed parts

2019-05-24 00:08 UTC, MartaSwierczewska commented on src/components/login/Login.css
> +input {
done xd

2019-05-24 00:10 UTC, MartaSwierczewska commented on src/components/login/Login.css
> +input {
albo nie

2019-05-24 00:22 UTC, Ajris approved these changes

2019-05-24 00:24 UTC, merged